name: PR review

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  issue_comment:
    types: [created]

jobs:
  review:
    if: github.event_name != 'issue_comment' || github.event.issue.pull_request != null
    permissions:
      contents: read
      id-token: write
      pull-requests: write
      issues: write
    uses: UGS-GIO/ugs-gha-pr-review/.github/workflows/review.yml@v1
    secrets: inherit
